# Generated by Django 3.0.4 on 2020-03-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='subscribe_plan',
        ),
    ]
